name: Deploy Test to Xserver

on:
  push:
    branches: ["main"]   # ← 既定ブランチが main 以外ならここを変更（例: "master"）

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 検証用ファイルを out/ に作る（本番のビルドはまだしない）
      - name: Create healthcheck file
        run: |
          mkdir -p out
          echo "deployed: $(date -u +'%Y-%m-%dT%H:%M:%SZ')" > out/healthcheck.txt

      - name: Upload to Xserver via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          server: ${{ secrets.XSERVER_HOST }}
          port: ${{ secrets.XSERVER_PORT }}     # ← 10022 で登録済みか確認
          username: ${{ secrets.XSERVER_USER }} # ← サーバーID
          ssh_private_key: ${{ secrets.XSERVER_SSH_KEY }}
          # 鍵にパスフレーズがある場合だけ ↓ を残す（無ければ削除OK）
          ssh_passphrase: ${{ secrets.XSERVER_SSH_PASSPHRASE }}
          local_path: './out/*'
          remote_path: ${{ secrets.XSERVER_REMOTE_PATH }}
          sftp_only: true
          delete_remote_files: false
